### ISSUE TITLE
problem when executing SpatioTemporalNN_Vicon

### ISSUE THREAD

**Issue by shiva-mtz** [avakanski/A-Deep-Learning-Framework-for-Assessing-Physical-Rehabilitation-Exercises#1]
Hi,
I have read your paper and I am working with your code , 
I ran every necessary functions to execute the code for Vicon Data in google Colab
Unfortunately in the last function, SpatioTemporalNN_Vicon, in part 13 of code , I have faced an error that I can not solve it.

while executing this line :
 concat_trunk = TempPyramid(seq_input_trunk, seq_input_trunk_2, seq_input_trunk_4, seq_input_trunk_8, timesteps, n_dim1)

an execption rased :
ValueError                                Traceback (most recent call last)
<ipython-input-19-df97ebf67258> in <module>()
     54 print(conv)
     55 
---> 56 concat_trunk = TempPyramid(seq_input_trunk, seq_input_trunk_2, seq_input_trunk_4, seq_input_trunk_8, timesteps, n_dim1)
     57 concat_left_arm = TempPyramid(seq_input_left_arm, seq_input_left_arm_2, seq_input_left_arm_4, seq_input_left_arm_8, timesteps, n_dim2)
     58 concat_right_arm = TempPyramid(seq_input_right_arm, seq_input_right_arm_2, seq_input_right_arm_4, seq_input_right_arm_8, timesteps, n_dim2)

6 frames
<ipython-input-12-f234a7dc141b> in TempPyramid(input_f, input_2, input_4, input_8, seq_len, n_dims)
     16 
     17     #### Recurrent layers
---> 18     x = concatenate([conv1, conv2, conv3, upsample1], axis=-1)
     19     return x

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/merge.py in concatenate(inputs, axis, **kwargs)
    929       A tensor, the concatenation of the inputs alongside axis `axis`.
    930   """
--> 931   return Concatenate(axis=axis, **kwargs)(inputs)
    932 
    933 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, *args, **kwargs)
    924     if _in_functional_construction_mode(self, inputs, args, kwargs, input_list):
    925       return self._functional_construction_call(inputs, args, kwargs,
--> 926                                                 input_list)
    927 
    928     # Maintains info about the `Layer.call` stack.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in _functional_construction_call(self, inputs, args, kwargs, input_list)
   1096         # Build layer if applicable (if the `build` method has been
   1097         # overridden).
-> 1098         self._maybe_build(inputs)
   1099         cast_inputs = self._maybe_cast_inputs(inputs, input_list)
   1100 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py in _maybe_build(self, inputs)
   2641         # operations.
   2642         with tf_utils.maybe_init_scope(self):
-> 2643           self.build(input_shapes)  # pylint:disable=not-callable
   2644       # We must set also ensure that the layer is marked as built, and the build
   2645       # shape is stored since user defined build functions may not be calling

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/tf_utils.py in wrapper(instance, input_shape)
    321     if input_shape is not None:
    322       input_shape = convert_shapes(input_shape, to_tuples=True)
--> 323     output_shape = fn(instance, input_shape)
    324     # Return shapes from `fn` as TensorShapes.
    325     if output_shape is not None:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/merge.py in build(self, input_shape)
    517             shape[axis] for shape in shape_set if shape[axis] is not None)
    518         if len(unique_dims) > 1:
--> 519           raise ValueError(err_msg)
    520 
    521   def _merge_function(self, inputs):

ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 68, 192), (None, 68, 192), (None, 34, 192), (None, 34, 192)]

would you please help me solve this problem ?
Thanks for your attention

**Comment by avakanski** [comment]
Hi Shiva, 
I ran the code SpatioTemporalNN_Vicon, but I didn't get any errors. I cannot tell what the problem is based on the posted error message. Could you please send me your jupyter notebook and I will have a look at the shapes of the inputs and will get back to you afterward. 
Alex

**Comment by shiva-mtz** [comment]
Hi Mr. Avakanski ,
Thanks a lot for your attention. I attached the .ipynb file here . I'll be grateful if you could help me.

Sepecial Thanks

[SpatioTemporalNN_Vicon.zip](https://github.com/avakanski/A-Deep-Learning-Framework-for-Assessing-Physical-Rehabilitation-Exercises/files/5618318/SpatioTemporalNN_Vicon.zip)

**Comment by shiva-mtz** [comment]
Hi Mr. Avakanski,
Thanks a lot for your attention. I attached the .ipybn file here. I'll be grateful if you could help me. 

Special Thanks
Shiva

[SpatioTemporalNN_Vicon.zip](https://github.com/avakanski/A-Deep-Learning-Framework-for-Assessing-Physical-Rehabilitation-Exercises/files/5618373/SpatioTemporalNN_Vicon.zip)

**Comment by avakanski** [comment]
Hi Shiva,
Attached please find the corrected file. I noticed that the values of the
strides in TempPyramid were changed from 1 to 2, which caused the errors
for concatenating the data. Please compare the 2 files to find the
differences.

The file should run now. Please change the epochs back to 500, and I also
added a few print lines for displaying the data shapes which you can remove.

If you have any other difficulties or questions please let me know.

Best,
Alex Vakanski

**Comment by avakanski** [comment]
[CorrectedFile.zip](https://github.com/avakanski/A-Deep-Learning-Framework-for-Assessing-Physical-Rehabilitation-Exercises/files/5618654/CorrectedFile.zip)

**Comment by shiva-mtz** [comment]
Hi Mr. Vakanski
Thanks so much! You're so helpful. I do appreciate your help.
The file was correct and worked perfectly.

 After all can I send an email to you and ask some questions about the paper ?
Because I am working on your paper for my thesis in university and I have some questions.

Special Thanks,
Shiva

**Comment by avakanski** [comment]
Hi Shiva,
Yes, I will be glad to answer your questions. Please send me an email to vakanski (at) uidaho (dot) edu.
Best,
Alex Vakanski
