### ISSUE TITLE
Cannot be reproduced

### ISSUE THREAD

**Issue by CyWang-Jade** [avakanski/A-Deep-Learning-Framework-for-Assessing-Physical-Rehabilitation-Exercises#3]
Dear author, can you share the data and score labels for the 10 movements?My reproduction is poor, there may be a problem with the data.I use the same method handles Reduced Data，but get a bad result.for example the result EX1.
![GMM_Loglikelihood_Scores_test](https://user-images.githubusercontent.com/56186523/176816696-2914f1e7-44a8-40cb-ad6d-af0513220bf5.png)
![GMM_Movement_Quality_Scores_test](https://user-images.githubusercontent.com/56186523/176816713-19e5ca07-0f7e-416e-a873-ebeb3501ea5e.png)

**Comment by avakanski** [comment]
Hello,
I am currently on vacation and I don't have access to the codes and data. I will take a look after July 15 and will get back to you.
Thanks.

**Comment by CyWang-Jade** [comment]
> Hello, I am currently on vacation and I don't have access to the codes and data. I will take a look after July 15 and will get back to you. Thanks.

Thank you very much. Have fun on vacation.

**Comment by avakanski** [comment]
Hi CyWang,

Please use the link below to download the data for all 10 exercises. The following notation is used: Train_X1 - Data_Correct, Test_X1 - Data_Incorrect, Train_Y1 - Labels_Correct, Test_Y1 - Labels_Incorrect. This notation is for Exercise 1, and the same notation applies for the other exercises: Train_X2, Train_X3, etc.

[https://vandalsuidaho-my.sharepoint.com/:u:/g/personal/vakanski_uidaho_edu/EbQT3nqON75ArJpbWo07C7gBS8e-UgDfbziRGYMLeL7ksw?e=NYLVpb](https://vandalsuidaho-my.sharepoint.com/:u:/g/personal/vakanski_uidaho_edu/EbQT3nqON75ArJpbWo07C7gBS8e-UgDfbziRGYMLeL7ksw?e=NYLVpb)

If you have troubles reproducing the results please send me your code for one exercise and I will have a look. 
Please also note that we have reproducible version of the code at 
[https://codeocean.com/capsule/7213982/tree/v3](https://codeocean.com/capsule/7213982/tree/v3)

Please let me know if you have any questions.

**Comment by CyWang-Jade** [comment]
> 

I'm truly grateful and best wish to you.

**Comment by CyWang-Jade** [comment]
> Hi CyWang,
> 
> Please use the link below to download the data for all 10 exercises. The following notation is used: Train_X1 - Data_Correct, Test_X1 - Data_Incorrect, Train_Y1 - Labels_Correct, Test_Y1 - Labels_Incorrect. This notation is for Exercise 1, and the same notation applies for the other exercises: Train_X2, Train_X3, etc.
> 
> https://vandalsuidaho-my.sharepoint.com/:u:/g/personal/vakanski_uidaho_edu/EbQT3nqON75ArJpbWo07C7gBS8e-UgDfbziRGYMLeL7ksw?e=NYLVpb
> 
> If you have troubles reproducing the results please send me your code for one exercise and I will have a look. Please also note that we have reproducible version of the code at https://codeocean.com/capsule/7213982/tree/v3
> 
> Please let me know if you have any questions.
I'm truly grateful and best wish to you.
